In [14]:
import torch
import numpy as np
torch.__version__

'2.8.0+cu129'

KHỞI TẠO TENSOR:  
***torch.tensor(n, device = X, dtype = Y)*** với n là giá trị khởi tạo của tensor, X là cuda/cpu, y là torch.dtype  
***tensor.ndim*** : chiều của tensor, ndim là một attribute của scalar  
***tensor.item()*** : trả về giá trị của tensor, đây là 1 phương thức   
***tensor.shape*** : trả về kích thước của tensor, là một attribute  

In [15]:
scalar = torch.tensor(7)
print(scalar.ndim, scalar, scalar.item())
vector = torch.tensor([2,3])
print(vector.ndim)
plane = torch.tensor([[1,2], [3,4]])
print(plane.ndim)
object = torch.tensor([[[1,3],[2,4]],
                       [[2,3],[1,6]]]) # tensor bậc 3
print(object.ndim, object.shape)
np_matrix = np.random.randint(0,100,size = 9).reshape(3,3)
tensor_matrix = torch.tensor(np_matrix)
print(tensor_matrix, tensor_matrix.ndim)


0 tensor(7) 7
1
2
3 torch.Size([2, 2, 2])
tensor([[97, 92, 53],
        [14, 22, 61],
        [79, 71, 41]], dtype=torch.int32) 2


In [16]:
cuda0 = torch.device('cuda:0')
gpu_tensor = torch.ones([2,4], dtype = torch.short, device = cuda0)

In [17]:
gpu_tensor.device

device(type='cuda', index=0)

Tạo random tensor:  
***torch.rand(size = (m,n))***  
Tạo zeros/ones tensor:   
***torch.zeros(size = (m,n))***   
Tạo tensor phân bổ:  
***torch.arange(start, end, step)***  
Tạo zeros tensor với kích thước bằng tensor khác:  
***torch.zeros_like(input)***  

In [18]:
rd_tensor = torch.rand(size = (3,3,3,3))*100
print(rd_tensor.shape, rd_tensor.ndim)
zeros = torch.zeros(size = (3,3), dtype = torch.short)
print(zeros)
even = torch.arange(0,11,2)
print(even)
zeros_even = torch.zeros_like(even)
print(zeros_even)

torch.Size([3, 3, 3, 3]) 4
tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]], dtype=torch.int16)
tensor([ 0,  2,  4,  6,  8, 10])
tensor([0, 0, 0, 0, 0, 0])


3 lệnh quan trọng để xử lý tensor là dtype trả về kiểu dữ liệu, shape trả về kích thước và device trả về CPU/GPU

In [19]:
print(f'rd_tensor có kích thước {rd_tensor.shape}\nloại dữ liệu {rd_tensor.dtype} \nthuộc {rd_tensor.device}')

rd_tensor có kích thước torch.Size([3, 3, 3, 3])
loại dữ liệu torch.float32 
thuộc cpu


***TENSOR OPERATIONS*** : cộng, trừ, nhân lần lượt, chia, nhân ma trận

In [20]:
t1 = torch.arange(1,6)
t2 = torch.arange(11,16)
print(t1)
print(t2)

tensor([1, 2, 3, 4, 5])
tensor([11, 12, 13, 14, 15])


In [21]:
sum = torch.add(t1,t2) # +
ele_wise_mul = torch.mul(t1,t2) # *
mat_mul = torch.matmul(t1,t2) # @
print(f"sum: {sum}\nele_wise_mul: {ele_wise_mul}\nmat_mul: {mat_mul}")

sum: tensor([12, 14, 16, 18, 20])
ele_wise_mul: tensor([11, 24, 39, 56, 75])
mat_mul: 205


Phép nhân ma trận @ có các quy tắc về chiều và kích thước của ma trận. *Trong đó số cột M1 phải bằng số hàng M2*  
Tức cho M1(m,n) và M2(p,q) thì M1xM2 phải thỏa **m=q** và trả về ma trận kích thước **(m,q)**  
**Quy tắc Inner-Dim** : 2 số phía trong bằng nhau

Trong NN, output y và input x liên hệ với nhau theo công thức :  
***y = x.W^T + b***  
trong đó W là ma trận trọng số, b là vector bias  


In [22]:
torch.manual_seed(1)
linear = torch.nn.Linear(in_features=2,  # Số chiều vector của Tensor đầu vào 
                         out_features=6) # Số chiều vector đầu ra 
tensor_A = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]], dtype=torch.float) 
output = linear(tensor_A)
tensor_A.shape

torch.Size([3, 2])

In [23]:
output, output.shape

(tensor([[-0.0016,  0.2511,  0.1309,  0.5103,  0.0276,  0.2631],
         [ 0.1029,  0.6408, -0.3524,  0.9389,  0.0511,  0.7251],
         [ 0.2074,  1.0304, -0.8357,  1.3674,  0.0745,  1.1871]],
        grad_fn=<AddmmBackward0>),
 torch.Size([3, 6]))

Linear tạo ra lớp tuyến tính  
**Quy trình làm việc** : *y = tensor_A(3x2) @ W(6x2)^T + b(6)*  
trong đó, sau khi tensor_A @ W^T sẽ ra ma trận 3x6, sau đó cộng với b

***TENSOR AGGREGATION***

In [24]:
t1 = t1.type(torch.float)
print(f"t1 : {t1} \nmean : {t1.mean()}\nmin: {t1.min()} \nmax: {t1.max()}\nsum: {t1.sum()}")

t1 : tensor([1., 2., 3., 4., 5.]) 
mean : 3.0
min: 1.0 
max: 5.0
sum: 15.0


***POSITIONAL MIN/MAX***  
Các hàm ***tensor.argmax()*** và ***tensor.argmin()*** được dùng để trả về index của max và min

In [25]:
t1.argmax(), t1.argmin()

(tensor(4), tensor(0))

***HÀM XỬ LÝ KHÔNG GIAN***: reshape(input, shape),  
*stack*: ghép các tensor lại theo 1 chiều mới,   
*squeeze*: loại bỏ chiều có giá trị = 1 (như 1 hàng, 1 cột, 1 độ cao)  
*unsqueeze*: thêm chiều bằng 1 

In [26]:
torch.manual_seed(42)
tensor1 = torch.randint(1,10, size = (4,3), device = cuda0)
tensor2 = torch.randint(1,10, size = (4,3), device = cuda0)
tensor1, tensor2

(tensor([[3, 7, 1],
         [7, 3, 4],
         [7, 8, 4],
         [9, 1, 6]], device='cuda:0'),
 tensor([[4, 7, 7],
         [3, 4, 5],
         [6, 1, 1],
         [7, 3, 2]], device='cuda:0'))

In [27]:
print(torch.reshape(tensor1, [2,6]))
dim0 = torch.stack([tensor1, tensor2])
dim1 = torch.stack((tensor1, tensor2),1)
dim2 = torch.stack((tensor1, tensor2),2)
print(dim2.shape)
print(dim1.shape)
print(dim0.shape)

tensor([[3, 7, 1, 7, 3, 4],
        [7, 8, 4, 9, 1, 6]], device='cuda:0')
torch.Size([4, 3, 2])
torch.Size([4, 2, 3])
torch.Size([2, 4, 3])


In [28]:
stacked_tensor1 = torch.stack([tensor1,tensor1,tensor1])
print(stacked_tensor1)
print(tensor1)
print(tensor1.unsqueeze(dim=0))

tensor([[[3, 7, 1],
         [7, 3, 4],
         [7, 8, 4],
         [9, 1, 6]],

        [[3, 7, 1],
         [7, 3, 4],
         [7, 8, 4],
         [9, 1, 6]],

        [[3, 7, 1],
         [7, 3, 4],
         [7, 8, 4],
         [9, 1, 6]]], device='cuda:0')
tensor([[3, 7, 1],
        [7, 3, 4],
        [7, 8, 4],
        [9, 1, 6]], device='cuda:0')
tensor([[[3, 7, 1],
         [7, 3, 4],
         [7, 8, 4],
         [9, 1, 6]]], device='cuda:0')


**INDEXING AND SLICING**

In [29]:
x = torch.reshape(tensor1, shape = (3,4))
x_3d = torch.stack([x,x,x])
x_3d

tensor([[[3, 7, 1, 7],
         [3, 4, 7, 8],
         [4, 9, 1, 6]],

        [[3, 7, 1, 7],
         [3, 4, 7, 8],
         [4, 9, 1, 6]],

        [[3, 7, 1, 7],
         [3, 4, 7, 8],
         [4, 9, 1, 6]]], device='cuda:0')

In [30]:
print(f"First square bracket:\n{x_3d[0]}\nĐây là batch số 0\n") 
print(f"Second square bracket: {x_3d[0][0]}\nĐây là cột số 0 của batch số 0\n") 
print(f"Third square bracket: {x_3d[0][0][0]}\nĐây là giá trị thứ 0 của cột số 0 của batch số 0")


First square bracket:
tensor([[3, 7, 1, 7],
        [3, 4, 7, 8],
        [4, 9, 1, 6]], device='cuda:0')
Đây là batch số 0

Second square bracket: tensor([3, 7, 1, 7], device='cuda:0')
Đây là cột số 0 của batch số 0

Third square bracket: 3
Đây là giá trị thứ 0 của cột số 0 của batch số 0


In [31]:
print(f"{x_3d}\n\n")
print(f"Lấy batch số 0: \n{x_3d[0,:,:]}, \n\nLấy hàng số 0-1 của cột số 1-2 của batch số 1:\n{x_3d[1,0:2,1:3]}")

tensor([[[3, 7, 1, 7],
         [3, 4, 7, 8],
         [4, 9, 1, 6]],

        [[3, 7, 1, 7],
         [3, 4, 7, 8],
         [4, 9, 1, 6]],

        [[3, 7, 1, 7],
         [3, 4, 7, 8],
         [4, 9, 1, 6]]], device='cuda:0')


Lấy batch số 0: 
tensor([[3, 7, 1, 7],
        [3, 4, 7, 8],
        [4, 9, 1, 6]], device='cuda:0'), 

Lấy hàng số 0-1 của cột số 1-2 của batch số 1:
tensor([[7, 1],
        [4, 7]], device='cuda:0')


***REPRODUCIBILITY***  
torch.manual_seed(seed) dùng để cố định tính ngẫu nhiên

***KÍCH HOẠT TORCH TRÊN GPU***  
khởi tạo **cuda0 = torch.device('cuda:0')** trước để định vị cuda0   
**gpu_tensor = torch.ones([2,4], dtype = torch.short, device = cuda0)**  
kết quả ta có gpu_tensor có khả năng xử lý bằng gpu  
Để chuyển 1 tensor có sẵn sang GPU/CPU ta dùng : **some_tensor.to(device)**  
VD: **gpu_tensor = cpu_tensor.to(cuda0)**

In [32]:
cpu_tensor = torch.ones(size = (4,2))
gpu_tensor = cpu_tensor.to(cuda0)
print(cpu_tensor.device, gpu_tensor.device)

cpu cuda:0
