***UNSUPERVISED LEARNING*** :   
Mô hình học không có target từ cấu trúc dữ liệu, bằng cách tìm các **thuộc tính** của dữ liệu, nó sẽ học cách *tìm ra feature* 

***CLUSTERING - PHÂN CỤM*** :  
Là việc nhóm các dữ liệu lại dựa trên mức độ giống nhau giữa chúng, là **"gió tầng nào gặp mây tầng đấy"**  

Việc phân cụm có thể mang lại ý nghĩa lớn, đặc biệt là khi không gian dữ liệu cực kì phức tạp và nhỏ lẻ

**K-Means** là một thuật toán phân cụm phổ biến trong học máy không giám sát. Thuật toán này chia tập dữ liệu thành *k* cụm (clusters) dựa trên sự tương đồng giữa các điểm dữ liệu. Quá trình thực hiện gồm các bước:

1. Chọn ngẫu nhiên *k* tâm cụm ban đầu.
2. Gán mỗi điểm dữ liệu vào cụm có tâm gần nhất.
3. Tính lại tâm cụm bằng cách lấy trung bình các điểm trong cụm.
4. Lặp lại bước 2 và 3 cho đến khi các tâm cụm không thay đổi hoặc đạt điều kiện dừng.

K-Means giúp phát hiện các nhóm dữ liệu có đặc điểm tương đồng mà không cần nhãn trước.

n_clusters : number of cluster (<k> in k-means)  
Max_iter : clustering stops after it doesn’t move anymore or after <max_iter> move  
n_init : repeat the algorithm <n_init> times to find out the best cluster distribution


In [1]:
import pandas as pd
import numpy as np 
import matplotlib.pyplot as plt
import seaborn as sns
data = pd.read_csv('housing.csv')
data.head()


MedInc  HouseAge  AveRooms  AveBedrms  Population  AveOccup  Latitude  \
0  8.3252      41.0  6.984127   1.023810       322.0  2.555556     37.88   
1  8.3014      21.0  6.238137   0.971880      2401.0  2.109842     37.86   
2  7.2574      52.0  8.288136   1.073446       496.0  2.802260     37.85   
3  5.6431      52.0  5.817352   1.073059       558.0  2.547945     37.85   
4  3.8462      52.0  6.281853   1.081081       565.0  2.181467     37.85   

   Longitude  MedHouseVal  
0    -122.23        4.526  
1    -122.22        3.585  
2    -122.24        3.521  
3    -122.25        3.413  
4    -122.25        3.422

In [2]:
X = data.copy()
X_orig = X.drop(columns=['MedHouseVal'])
y = X.pop('MedHouseVal')

In [3]:
features = ['Latitude', 'Longitude', 'MedInc']

In [4]:
X_train = X.loc[:, features] # Tạo cluster thu nhập trung bình theo từng cụm địa phương

In [5]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)

In [6]:
from sklearn.cluster import KMeans
kmeans = KMeans(n_clusters=8, max_iter=10, n_init = 3, random_state=0)
KM = kmeans.fit(X_train)

# Convert X_train_ori back to DataFrame for cluster assignment
X['Cluster'] = KM.labels_ # labels có tác dụng gán nhãn cho từng cụm

In [7]:
X.head()

MedInc  HouseAge  AveRooms  AveBedrms  Population  AveOccup  Latitude  \
0  8.3252      41.0  6.984127   1.023810       322.0  2.555556     37.88   
1  8.3014      21.0  6.238137   0.971880      2401.0  2.109842     37.86   
2  7.2574      52.0  8.288136   1.073446       496.0  2.802260     37.85   
3  5.6431      52.0  5.817352   1.073059       558.0  2.547945     37.85   
4  3.8462      52.0  6.281853   1.081081       565.0  2.181467     37.85   

   Longitude  Cluster  
0    -122.23        2  
1    -122.22        2  
2    -122.24        2  
3    -122.25        2  
4    -122.25        3

Centroid [33.88, -118.00, 4.46] nghĩa là: điểm trung bình của cụm 1 có vị trí khoảng vĩ độ 33.88, kinh độ -118.00, và Medinc bằng 4.46.  
Inertia : 


In [ ]:
print('cột cluster mới được thêm vào :')
print(X['Cluster'].head())
print(f'cluster center - centroid : \n{KM.cluster_centers_}') 
print(f'inertia : \n{KM.inertia_}') #Inertia được đánh giá bằng cách nhìn đồ thị

cột cluster mới được thêm vào :
0    2
1    2
2    2
3    2
4    3
Name: Cluster, dtype: int32
cluster center - centroid : 
[[ 0.23804863 -0.08359053 -0.66142802]
 [-0.82791253  0.79733616  0.18085347]
 [ 0.94101539 -1.20998039  1.58045054]
 [ 1.02291572 -1.17010961  0.18394716]
 [-0.8264717   0.75238782  1.41101601]
 [-0.85634472  0.89258559 -0.7666361 ]
 [ 1.38254355 -1.16294399 -0.77697063]
 [-0.40721973  0.23570012  4.17083474]]
inertia : 
7714.027270467272


In [ ]:
sns.relplot(data=X, x='Longitude', y='Latitude', hue='Cluster', palette='Set1')
# relplot là scatter plot nâng cao, có thể thêm màu sắc, kích thước, kiểu marker dựa trên các biến khác nhau

Nhận thấy tại k = 8, đồ thị đột ngột chững lại => Elbow tại đó - k=8 là giá trị hợp lý  
Trong khi đó, n_init có giá trị bằng nhau từ 3-9 => chọn 3, còn max_iter = 10 để tối ưu hiệu suất  

Sau khi đã tuning hyperparameter, ta đã có thể predict những điểm mới sẽ thuộc cụm nào  

Sau khi fit, K-means đã xác định được 8 tâm cụm.

fit_predict trả về vector tâm cụm gần nhất với điểm

fit_transform tính khoảng cách từ mỗi điểm mới đến mỗi centroid, trả về np.array của những list ứng với   
KC đến từng centroid của mỗi điểm

In [60]:
X_cd = kmeans.fit_transform(X_train)

In [ ]:
X_cd.shape #mảng 2D với số hàng = số mẫu, số cột = số cụm

In [62]:
X_cd = pd.DataFrame(X_cd, columns=[f'cd_{i}' for i in range(X_cd.shape[1])])
X = pd.concat([X, X_cd], axis=1)

In [69]:
X.shape

(20640, 17)

In [70]:
X_orig.shape

(20640, 8)

In [ ]:
# X : dữ liệu đã kmeans
# X_orig : dữ liệu chưa kmeans

Lúc này X đã có thêm 8 cột thể hiện tương quan giữa median income và địa phương, để xem đây có phải là thông tin giá trị không  
ta có thể sử dụng MAE để so sánh 2 mô hình RF giữa có và không có kmeans

In [ ]:
from sklearn.model_selection import cross_val_score
def data_compare(model, Xtrain, ytrain):
    scores = cross_val_score(
        estimator=model,
        X=Xtrain,          # dữ liệu đầu vào
        y=ytrain,              # nhãn
        cv=5,             # số fold, mặc định = 5
        scoring='neg_mean_absolute_error'  # metric
    )
    cvs_score = -1*scores
    return cvs_score.mean()

In [71]:
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import cross_val_score

# model linear regression
lr = LinearRegression()

# dữ liệu gốc
score_orig = -cross_val_score(lr, X_orig, y, cv=5, scoring='neg_mean_absolute_error').mean()

# dữ liệu đã KMeans
score_kmeans = -cross_val_score(lr, X, y, cv=5, scoring='neg_mean_absolute_error').mean()

print("MAE gốc:", score_orig)
print("MAE có KMeans:", score_kmeans)


MAE gốc: 0.5474961907866827
MAE có KMeans: 0.5345621197480886
